use rand::prelude::SliceRandom;

pub fn random_emoji() -> String {
  let allowed_emojis: Vec<String> = vec![
    "🛒".to_string(),
    "🍎".to_string(),
    "🍏".to_string(),
    "🍐".to_string(),
    "🍊".to_string(),
    "🍋".to_string(),
    "🍌".to_string(),
    "🍉".to_string(),
    "🍇".to_string(),
    "🍓".to_string(),
    "🍈".to_string(),
    "🍒".to_string(),
    "🍑".to_string(),
    "🍍".to_string(),
    "🥝".to_string(),
    "🥑".to_string(),
    "🍅".to_string(),
    "🍆".to_string(),
    "🥒".to_string(),
    "🥕".to_string(),
    "🌽".to_string(),
    "🥔".to_string(),
    "🍠".to_string(),
    "🌰".to_string(),
    "🥜".to_string(),
    "🍯".to_string(),
    "🥐".to_string(),
    "🍞".to_string(),
    "🥖".to_string(),
    "🧀".to_string(),
    "🥚".to_string(),
    "🍳".to_string(),
    "🥓".to_string(),
    "🥞".to_string(),
    "🍤".to_string(),
    "🍗".to_string(),
    "🍖".to_string(),
    "🍕".to_string(),
    "🌭".to_string(),
    "🍔".to_string(),
    "🍟".to_string(),
    "🥙".to_string(),
    "🌮".to_string(),
    "🌯".to_string(),
    "🥗".to_string(),
    "🥘".to_string(),
    "🍝".to_string(),
    "🍜".to_string(),
    "🍲".to_string(),
    "🍛".to_string(),
    "🍣".to_string(),
    "🍱".to_string(),
    "🍤".to_string(),
    "🍙".to_string(),
    "🍚".to_string(),
    "🍘".to_string(),
    "🍥".to_string(),
    "🥠".to_string(),
    "🍢".to_string(),
    "🍡".to_string(),
    "🍧".to_string(),
    "🍨".to_string(),
    "🍦".to_string(),
    "🍰".to_string(),
    "🎂".to_string(),
    "🍮".to_string(),
    "🍭".to_string(),
    "🍬".to_string(),
    "🍫".to_string(),
    "🍿".to_string(),
    "🍩".to_string(),
    "🍪".to_string(),
    "🌈".to_string(),
    "🎁".to_string(),
    "🐧".to_string(),
    "🐦".to_string(),
    "🐤".to_string(),
    "🐣".to_string(),
    "🐥".to_string(),
    "🐔".to_string(),
    "🐢".to_string(),
    "🐛".to_string(),
    "🐝".to_string(),
    "🐜".to_string(),
    "🐞".to_string(),
    "🐌".to_string(),
    "🐙".to_string(),
    "🐚".to_string(),
    "🐠".to_string(),
    "🐟".to_string(),
    "🐬".to_string(),
    "🐳".to_string(),
    "🐋".to_string(),
    "🐄".to_string(),
    "🐏".to_string(),
    "🐀".to_string(),
    "🐃".to_string(),
    "🐅".to_string(),
    "🐇".to_string(),
    "🐉".to_string(),
    "🐎".to_string(),
    "🐐".to_string(),
    "🐓".to_string(),
    "🐕".to_string(),
    "🐖".to_string(),
    "🐁".to_string(),
    "🐂".to_string(),
    "🦞".to_string(),
    "🦀".to_string(),
    "🦐".to_string(),
    "🦑".to_string(),
    "🦋".to_string(),
    "🦔".to_string(),
    "🦇".to_string(),
    "🦅".to_string(),
    "🦆".to_string(),
    "🌈".to_string(),
    "🦄".to_string(),
    "🌸".to_string(),
    "🌷".to_string(),
    "🌹".to_string(),
    "🌺".to_string(),
    "🌻".to_string(),
    "🌼".to_string(),
    "✌️".to_string(),
    "👌".to_string(),
    "🖖".to_string(),
    "🤌".to_string(),
    "🤟".to_string(),
    "🤘".to_string(),
    "🤙".to_string(),
    "🤞".to_string(),
    "🙌".to_string(),
    "👀".to_string(),
    "👁️".to_string(),
    "👅".to_string(),
    "👂".to_string(),
    "👃".to_string(),
    "👄".to_string(),
  ];
  let emoji = allowed_emojis.choose(&mut rand::thread_rng());
  if let Some(emoji) = emoji {
    emoji.to_string()
  } else {
    "🦀".to_string() // crab
  }
}

#[cfg(test)]
mod ci_unit {
  use super::*;

  #[test]
  fn is_emoji() {
    let emoji = random_emoji();
    assert!(emojis::get(&emoji).is_some());
  }
}
