-- Your SQL goes here
CREATE TABLE transactions (
  id VARCHAR(255) PRIMARY KEY,
  group_id VARCHAR(255) NOT NULL REFERENCES groups(id) ON DELETE CASCADE,
  from_id VARCHAR(255) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  to_id VARCHAR(255) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  amount BIGINT NOT NULL,
  method TEXT NOT NULL,
  confirmed BOOLEAN NOT NULL,
  deleted BOOLEAN NOT NULL,
  created_at BIGINT NOT NULL
)