-- Your SQL goes here
CREATE TABLE debts (
  id VARCHAR(255) PRIMARY KEY,
  group_id VARCHAR(255) NOT NULL REFERENCES groups(id) ON DELETE CASCADE,
  from_id VARCHAR(255) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  to_id VARCHAR(255) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  amount BIGINT NOT NULL,
  created_at BIGINT NOT NULL
)